### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by QuiiBz** [QuiiBz/squid#63]
Roadmap of new features/improvements for Squid:

- [ ] Cloud SSH Hosts
- [x] Plugins / themes system (#65)
- [ ] Draggable tabs
- [x] Custom CSS in config
- [x] "Open Squid here" macOS integration (#68)
- [ ] "Open Squid here" Windows integration (#70) 
- [x] Vibrancy
- [x] CLI (#73)
- [ ] Right-click features (#75)
- [ ] Add V8 snapshots (#85)
- [ ] Write documentation
- [ ] Improve internal code:
  - [x] Replace Redux by Context API (#64)
  - [x] Write tests (#67)
  - [ ] Refactor React code (#76)
